"""Storage backends for the VasoAnalyzer project format."""

from . import sqlite  # Skeleton package exposing upcoming modular split.
from .sqlite_store import (
    ProjectStore,
    SCHEMA_VERSION,
    add_dataset,
    add_or_update_asset,
    add_result,
    create_project,
    get_dataset_meta,
    get_asset_bytes,
    get_events,
    get_results,
    list_assets,
    get_trace,
    iter_datasets,
    open_project,
    pack_bundle,
    save_project,
    save_project_as,
    unpack_bundle,
    write_autosave,
    restore_autosave,
    update_dataset_meta,
)

__all__ = [
    "sqlite",
    "ProjectStore",
    "SCHEMA_VERSION",
    "add_dataset",
    "add_or_update_asset",
    "add_result",
    "create_project",
    "get_dataset_meta",
    "get_asset_bytes",
    "get_events",
    "get_results",
    "list_assets",
    "get_trace",
    "iter_datasets",
    "open_project",
    "pack_bundle",
    "save_project",
    "save_project_as",
    "unpack_bundle",
    "write_autosave",
    "restore_autosave",
    "update_dataset_meta",
]
