name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Tests (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        shell: bash

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .[dev]
        shell: bash

      - name: Ruff
        run: ruff check src tests
        shell: bash

      - name: MyPy
        run: mypy src scripts tests
        shell: bash

      - name: Pytest
        env:
          QT_QPA_PLATFORM: offscreen
          MPLBACKEND: Agg
          PYTHONPATH: src
        run: pytest
        shell: bash

      - name: Pytest (event_labels_v2)
        env:
          QT_QPA_PLATFORM: offscreen
          MPLBACKEND: Agg
          PYTHONPATH: src
          VA_FEATURES: event_labels_v2
        run: pytest
        shell: bash
